### ISSUE TITLE
椎咲良田

### ISSUE THREAD

**Issue by sanshiliuxiao** [sanshiliuxiao/comments#126]
https://sanshiliuxiao.top/friends/

**Comment by sanshiliuxiao** [comment]
## 友链申请格式

```yml
name: 椎咲良田
siteUrl: https://sanshiliuxiao.top
siteImg: https://i.loli.net/2019/01/28/5c4ed2421e164.jpg
avatar: https://i.loli.net/2019/01/28/5c4eca46c1d0b.png
```
